services:
  zipkin:
    image: 'openzipkin/zipkin:latest'
    container_name: zipkin
    ports:
      - '9411:9411'
    networks:
      - gateway-network


  redis:
    image: 'redis/redis-stack:7.2.0-v17'
    container_name: redis-stack-server
    ports:
      - '6379:6379'
    networks:
      - gateway-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - gateway-network

  postgres:
    image: postgres:13
    container_name: postgres-for-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gateway-network

networks:
  gateway-network:
    driver: bridge

volumes:
  postgres_data: